#include "../../../../include/sgf/platform/input/key_mapper.h"
#include <GLFW/glfw3.h>

namespace sgf_core {
    std::unordered_map<int32_t, Key> KeyMapper::toSGFMap = {
        { GLFW_KEY_SPACE, Key::SPACE },
        { GLFW_KEY_APOSTROPHE, Key::APOSTROPHE },
        { GLFW_KEY_COMMA, Key::COMMA },
        { GLFW_KEY_MINUS, Key::MINUS },
        { GLFW_KEY_PERIOD, Key::PERIOD },
        { GLFW_KEY_SLASH, Key::SLASH },
        { GLFW_KEY_0, Key::KEYBOARD_0 },
        { GLFW_KEY_1, Key::KEYBOARD_1 },
        { GLFW_KEY_2, Key::KEYBOARD_2 },
        { GLFW_KEY_3, Key::KEYBOARD_3 },
        { GLFW_KEY_4, Key::KEYBOARD_4 },
        { GLFW_KEY_5, Key::KEYBOARD_5 },
        { GLFW_KEY_6, Key::KEYBOARD_6 },
        { GLFW_KEY_7, Key::KEYBOARD_7 },
        { GLFW_KEY_8, Key::KEYBOARD_8 },
        { GLFW_KEY_9, Key::KEYBOARD_9 },
        { GLFW_KEY_SEMICOLON, Key::SEMICOLON },
        { GLFW_KEY_EQUAL, Key::EQUAL },
        { GLFW_KEY_A, Key::A },
        { GLFW_KEY_B, Key::B },
        { GLFW_KEY_C, Key::C },
        { GLFW_KEY_D, Key::D },
        { GLFW_KEY_E, Key::E },
        { GLFW_KEY_F, Key::F },
        { GLFW_KEY_G, Key::G },
        { GLFW_KEY_H, Key::H },
        { GLFW_KEY_I, Key::I },
        { GLFW_KEY_J, Key::J },
        { GLFW_KEY_K, Key::K },
        { GLFW_KEY_L, Key::L },
        { GLFW_KEY_M, Key::M },
        { GLFW_KEY_N, Key::N },
        { GLFW_KEY_O, Key::O },
        { GLFW_KEY_P, Key::P },
        { GLFW_KEY_Q, Key::Q },
        { GLFW_KEY_R, Key::R },
        { GLFW_KEY_S, Key::S },
        { GLFW_KEY_T, Key::T },
        { GLFW_KEY_U, Key::U },
        { GLFW_KEY_V, Key::V },
        { GLFW_KEY_W, Key::W },
        { GLFW_KEY_X, Key::X },
        { GLFW_KEY_Y, Key::Y },
        { GLFW_KEY_Z, Key::Z },
        { GLFW_KEY_LEFT_BRACKET, Key::LEFT_BRACKET },
        { GLFW_KEY_BACKSLASH, Key::BACKSLASH },
        { GLFW_KEY_RIGHT_BRACKET, Key::RIGHT_BRACKET },
        { GLFW_KEY_WORLD_1, Key::WORLD_1 },
        { GLFW_KEY_WORLD_2, Key::WORLD_2 },
        { GLFW_KEY_ESCAPE, Key::ESCAPE },
        { GLFW_KEY_ENTER, Key::ENTER },
        { GLFW_KEY_TAB, Key::TAB },
        { GLFW_KEY_BACKSPACE, Key::BACKSPACE },
        { GLFW_KEY_INSERT, Key::INSERT },
        { GLFW_KEY_DELETE, Key::DELETE },
        { GLFW_KEY_RIGHT, Key::RIGHT },
        { GLFW_KEY_LEFT, Key::LEFT },
        { GLFW_KEY_DOWN, Key::DOWN },
        { GLFW_KEY_UP, Key::UP },
        { GLFW_KEY_PAGE_UP, Key::PAGE_UP },
        { GLFW_KEY_PAGE_DOWN, Key::PAGE_DOWN },
        { GLFW_KEY_HOME, Key::HOME },
        { GLFW_KEY_END, Key::END },
        { GLFW_KEY_CAPS_LOCK, Key::CAPS_LOCK },
        { GLFW_KEY_SCROLL_LOCK, Key::SCROLL_LOCK },
        { GLFW_KEY_NUM_LOCK, Key::NUM_LOCK },
        { GLFW_KEY_PRINT_SCREEN, Key::PRINT_SCREEN },
        { GLFW_KEY_PAUSE, Key::PAUSE },
        { GLFW_KEY_F1, Key::F1 },
        { GLFW_KEY_F2, Key::F2 },
        { GLFW_KEY_F3, Key::F3 },
        { GLFW_KEY_F4, Key::F4 },
        { GLFW_KEY_F5, Key::F5 },
        { GLFW_KEY_F6, Key::F6 },
        { GLFW_KEY_F7, Key::F7 },
        { GLFW_KEY_F8, Key::F8 },
        { GLFW_KEY_F9, Key::F9 },
        { GLFW_KEY_F10, Key::F10 },
        { GLFW_KEY_F11, Key::F11 },
        { GLFW_KEY_F12, Key::F12 },
        { GLFW_KEY_F13, Key::F13 },
        { GLFW_KEY_F14, Key::F14 },
        { GLFW_KEY_F15, Key::F15 },
        { GLFW_KEY_F16, Key::F16 },
        { GLFW_KEY_F17, Key::F17 },
        { GLFW_KEY_F18, Key::F18 },
        { GLFW_KEY_F19, Key::F19 },
        { GLFW_KEY_F20, Key::F20 },
        { GLFW_KEY_F21, Key::F21 },
        { GLFW_KEY_F22, Key::F22 },
        { GLFW_KEY_F23, Key::F23 },
        { GLFW_KEY_F24, Key::F24 },
        { GLFW_KEY_F25, Key::F25 },
        { GLFW_KEY_KP_0, Key::KEYPAD_0 },
        { GLFW_KEY_KP_1, Key::KEYPAD_1 },
        { GLFW_KEY_KP_2, Key::KEYPAD_2 },
        { GLFW_KEY_KP_3, Key::KEYPAD_3 },
        { GLFW_KEY_KP_4, Key::KEYPAD_4 },
        { GLFW_KEY_KP_5, Key::KEYPAD_5 },
        { GLFW_KEY_KP_6, Key::KEYPAD_6 },
        { GLFW_KEY_KP_7, Key::KEYPAD_7 },
        { GLFW_KEY_KP_8, Key::KEYPAD_8 },
        { GLFW_KEY_KP_9, Key::KEYPAD_9 },
        { GLFW_KEY_KP_DECIMAL, Key::KEYPAD_DECIMAL },
        { GLFW_KEY_KP_DIVIDE, Key::KEYPAD_DIVIDE },
        { GLFW_KEY_KP_MULTIPLY, Key::KEYPAD_MULTIPLY },
        { GLFW_KEY_KP_SUBTRACT, Key::KEYPAD_SUBTRACT },
        { GLFW_KEY_KP_ADD, Key::KEYPAD_ADD },
        { GLFW_KEY_KP_ENTER, Key::KEYPAD_ENTER },
        { GLFW_KEY_KP_EQUAL, Key::KEYPAD_EQUAL },
        { GLFW_KEY_LEFT_SHIFT, Key::LEFT_SHIFT },
        { GLFW_KEY_LEFT_CONTROL, Key::LEFT_CONTROL },
        { GLFW_KEY_LEFT_ALT, Key::LEFT_ALT },
        { GLFW_KEY_LEFT_SUPER, Key::LEFT_SUPER },
        { GLFW_KEY_RIGHT_SHIFT, Key::RIGHT_SHIFT },
        { GLFW_KEY_RIGHT_CONTROL, Key::RIGHT_CONTROL },
        { GLFW_KEY_RIGHT_ALT, Key::RIGHT_ALT },
        { GLFW_KEY_RIGHT_SUPER, Key::RIGHT_SUPER },
        { GLFW_KEY_MENU, Key::MENU }
    };

    std::unordered_map<Key, int32_t> KeyMapper::toGLFWMap = {
        { Key::SPACE, GLFW_KEY_SPACE },
        { Key::APOSTROPHE, GLFW_KEY_APOSTROPHE },
        { Key::COMMA, GLFW_KEY_COMMA },
        { Key::MINUS, GLFW_KEY_MINUS },
        { Key::PERIOD, GLFW_KEY_PERIOD },
        { Key::SLASH, GLFW_KEY_SLASH },
        { Key::KEYBOARD_0, GLFW_KEY_0 },
        { Key::KEYBOARD_1, GLFW_KEY_1 },
        { Key::KEYBOARD_2, GLFW_KEY_2 },
        { Key::KEYBOARD_3, GLFW_KEY_3 },
        { Key::KEYBOARD_4, GLFW_KEY_4 },
        { Key::KEYBOARD_5, GLFW_KEY_5 },
        { Key::KEYBOARD_6, GLFW_KEY_6 },
        { Key::KEYBOARD_7, GLFW_KEY_7 },
        { Key::KEYBOARD_8, GLFW_KEY_8 },
        { Key::KEYBOARD_9, GLFW_KEY_9 },
        { Key::SEMICOLON, GLFW_KEY_SEMICOLON },
        { Key::EQUAL, GLFW_KEY_EQUAL },
        { Key::A, GLFW_KEY_A },
        { Key::B, GLFW_KEY_B },
        { Key::C, GLFW_KEY_C },
        { Key::D, GLFW_KEY_D },
        { Key::E, GLFW_KEY_E },
        { Key::F, GLFW_KEY_F },
        { Key::G, GLFW_KEY_G },
        { Key::H, GLFW_KEY_H },
        { Key::I, GLFW_KEY_I },
        { Key::J, GLFW_KEY_J },
        { Key::K, GLFW_KEY_K },
        { Key::L, GLFW_KEY_L },
        { Key::M, GLFW_KEY_M },
        { Key::N, GLFW_KEY_N },
        { Key::O, GLFW_KEY_O },
        { Key::P, GLFW_KEY_P },
        { Key::Q, GLFW_KEY_Q },
        { Key::R, GLFW_KEY_R },
        { Key::S, GLFW_KEY_S },
        { Key::T, GLFW_KEY_T },
        { Key::U, GLFW_KEY_U },
        { Key::V, GLFW_KEY_V },
        { Key::W, GLFW_KEY_W },
        { Key::X, GLFW_KEY_X },
        { Key::Y, GLFW_KEY_Y },
        { Key::Z, GLFW_KEY_Z },
        { Key::LEFT_BRACKET, GLFW_KEY_LEFT_BRACKET },
        { Key::BACKSLASH, GLFW_KEY_BACKSLASH },
        { Key::RIGHT_BRACKET, GLFW_KEY_RIGHT_BRACKET },
        { Key::WORLD_1, GLFW_KEY_WORLD_1 },
        { Key::WORLD_2, GLFW_KEY_WORLD_2 },
        { Key::ESCAPE, GLFW_KEY_ESCAPE },
        { Key::ENTER, GLFW_KEY_ENTER },
        { Key::TAB, GLFW_KEY_TAB },
        { Key::BACKSPACE, GLFW_KEY_BACKSPACE },
        { Key::INSERT, GLFW_KEY_INSERT },
        { Key::DELETE, GLFW_KEY_DELETE },
        { Key::RIGHT, GLFW_KEY_RIGHT },
        { Key::LEFT, GLFW_KEY_LEFT },
        { Key::DOWN, GLFW_KEY_DOWN },
        { Key::UP, GLFW_KEY_UP },
        { Key::PAGE_UP, GLFW_KEY_PAGE_UP },
        { Key::PAGE_DOWN, GLFW_KEY_PAGE_DOWN },
        { Key::HOME, GLFW_KEY_HOME },
        { Key::END, GLFW_KEY_END },
        { Key::CAPS_LOCK, GLFW_KEY_CAPS_LOCK },
        { Key::SCROLL_LOCK, GLFW_KEY_SCROLL_LOCK },
        { Key::NUM_LOCK, GLFW_KEY_NUM_LOCK },
        { Key::PRINT_SCREEN, GLFW_KEY_PRINT_SCREEN },
        { Key::PAUSE, GLFW_KEY_PAUSE },
        { Key::F1, GLFW_KEY_F1 },
        { Key::F2, GLFW_KEY_F2 },
        { Key::F3, GLFW_KEY_F3 },
        { Key::F4, GLFW_KEY_F4 },
        { Key::F5, GLFW_KEY_F5 },
        { Key::F6, GLFW_KEY_F6 },
        { Key::F7, GLFW_KEY_F7 },
        { Key::F8, GLFW_KEY_F8 },
        { Key::F9, GLFW_KEY_F9 },
        { Key::F10, GLFW_KEY_F10 },
        { Key::F11, GLFW_KEY_F11 },
        { Key::F12, GLFW_KEY_F12 },
        { Key::F13, GLFW_KEY_F13 },
        { Key::F14, GLFW_KEY_F14 },
        { Key::F15, GLFW_KEY_F15 },
        { Key::F16, GLFW_KEY_F16 },
        { Key::F17, GLFW_KEY_F17 },
        { Key::F18, GLFW_KEY_F18 },
        { Key::F19, GLFW_KEY_F19 },
        { Key::F20, GLFW_KEY_F20 },
        { Key::F21, GLFW_KEY_F21 },
        { Key::F22, GLFW_KEY_F22 },
        { Key::F23, GLFW_KEY_F23 },
        { Key::F24, GLFW_KEY_F24 },
        { Key::F25, GLFW_KEY_F25 },
        { Key::KEYPAD_0, GLFW_KEY_KP_0 },
        { Key::KEYPAD_1, GLFW_KEY_KP_1 },
        { Key::KEYPAD_2, GLFW_KEY_KP_2 },
        { Key::KEYPAD_3, GLFW_KEY_KP_3 },
        { Key::KEYPAD_4, GLFW_KEY_KP_4 },
        { Key::KEYPAD_5, GLFW_KEY_KP_5 },
        { Key::KEYPAD_6, GLFW_KEY_KP_6 },
        { Key::KEYPAD_7, GLFW_KEY_KP_7 },
        { Key::KEYPAD_8, GLFW_KEY_KP_8 },
        { Key::KEYPAD_9, GLFW_KEY_KP_9 },
        { Key::KEYPAD_DECIMAL, GLFW_KEY_KP_DECIMAL },
        { Key::KEYPAD_DIVIDE, GLFW_KEY_KP_DIVIDE },
        { Key::KEYPAD_MULTIPLY, GLFW_KEY_KP_MULTIPLY },
        { Key::KEYPAD_SUBTRACT, GLFW_KEY_KP_SUBTRACT },
        { Key::KEYPAD_ADD, GLFW_KEY_KP_ADD },
        { Key::KEYPAD_ENTER, GLFW_KEY_KP_ENTER },
        { Key::KEYPAD_EQUAL, GLFW_KEY_KP_EQUAL },
        { Key::LEFT_SHIFT, GLFW_KEY_LEFT_SHIFT },
        { Key::LEFT_CONTROL, GLFW_KEY_LEFT_CONTROL },
        { Key::LEFT_ALT, GLFW_KEY_LEFT_ALT },
        { Key::LEFT_SUPER, GLFW_KEY_LEFT_SUPER },
        { Key::RIGHT_SHIFT, GLFW_KEY_RIGHT_SHIFT },
        { Key::RIGHT_CONTROL, GLFW_KEY_RIGHT_CONTROL },
        { Key::RIGHT_ALT, GLFW_KEY_RIGHT_ALT },
        { Key::RIGHT_SUPER, GLFW_KEY_RIGHT_SUPER },
        { Key::MENU, GLFW_KEY_MENU }
    };

    std::unordered_map<Key, std::string> KeyMapper::toNameMap = {
        { Key::SPACE, "SPACE" },
        { Key::APOSTROPHE, "APOSTROPHE" },
        { Key::COMMA, "COMMA" },
        { Key::MINUS, "MINUS" },
        { Key::PERIOD, "PERIOD" },
        { Key::SLASH, "SLASH" },
        { Key::KEYBOARD_0, "0" },
        { Key::KEYBOARD_1, "1" },
        { Key::KEYBOARD_2, "2" },
        { Key::KEYBOARD_3, "3" },
        { Key::KEYBOARD_4, "4" },
        { Key::KEYBOARD_5, "5" },
        { Key::KEYBOARD_6, "6" },
        { Key::KEYBOARD_7, "7" },
        { Key::KEYBOARD_8, "8" },
        { Key::KEYBOARD_9, "9" },
        { Key::SEMICOLON, "SEMICOLON" },
        { Key::EQUAL, "EQUAL" },
        { Key::A, "A" },
        { Key::B, "B" },
        { Key::C, "C" },
        { Key::D, "D" },
        { Key::E, "E" },
        { Key::F, "F" },
        { Key::G, "G" },
        { Key::H, "H" },
        { Key::I, "I" },
        { Key::J, "J" },
        { Key::K, "K" },
        { Key::L, "L" },
        { Key::M, "M" },
        { Key::N, "N" },
        { Key::O, "O" },
        { Key::P, "P" },
        { Key::Q, "Q" },
        { Key::R, "R" },
        { Key::S, "S" },
        { Key::T, "T" },
        { Key::U, "U" },
        { Key::V, "V" },
        { Key::W, "W" },
        { Key::X, "X" },
        { Key::Y, "Y" },
        { Key::Z, "Z" },
        { Key::LEFT_BRACKET, "LEFT_BRACKET" },
        { Key::BACKSLASH, "BACKSLASH" },
        { Key::RIGHT_BRACKET, "RIGHT_BRACKET" },
        { Key::WORLD_1, "WORLD_1" },
        { Key::WORLD_2, "WORLD_2" },
        { Key::ESCAPE, "ESCAPE" },
        { Key::ENTER, "ENTER" },
        { Key::TAB, "TAB" },
        { Key::BACKSPACE, "BACKSPACE" },
        { Key::INSERT, "INSERT" },
        { Key::DELETE, "DELETE" },
        { Key::RIGHT, "RIGHT" },
        { Key::LEFT, "LEFT" },
        { Key::DOWN, "DOWN" },
        { Key::UP, "UP" },
        { Key::PAGE_UP, "PAGE_UP" },
        { Key::PAGE_DOWN, "PAGE_DOWN" },
        { Key::HOME, "HOME" },
        { Key::END, "END" },
        { Key::CAPS_LOCK, "CAPS_LOCK" },
        { Key::SCROLL_LOCK, "SCROLL_LOCK" },
        { Key::NUM_LOCK, "NUM_LOCK" },
        { Key::PRINT_SCREEN, "PRINT_SCREEN" },
        { Key::PAUSE, "PAUSE" },
        { Key::F1, "F1" },
        { Key::F2, "F2" },
        { Key::F3, "F3" },
        { Key::F4, "F4" },
        { Key::F5, "F5" },
        { Key::F6, "F6" },
        { Key::F7, "F7" },
        { Key::F8, "F8" },
        { Key::F9, "F9" },
        { Key::F10, "F10" },
        { Key::F11, "F11" },
        { Key::F12, "F12" },
        { Key::F13, "F13" },
        { Key::F14, "F14" },
        { Key::F15, "F15" },
        { Key::F16, "F16" },
        { Key::F17, "F17" },
        { Key::F18, "F18" },
        { Key::F19, "F19" },
        { Key::F20, "F20" },
        { Key::F21, "F21" },
        { Key::F22, "F22" },
        { Key::F23, "F23" },
        { Key::F24, "F24" },
        { Key::F25, "F25" },
        { Key::KEYPAD_0, "KP_0" },
        { Key::KEYPAD_1, "KP_1" },
        { Key::KEYPAD_2, "KP_2" },
        { Key::KEYPAD_3, "KP_3" },
        { Key::KEYPAD_4, "KP_4" },
        { Key::KEYPAD_5, "KP_5" },
        { Key::KEYPAD_6, "KP_6" },
        { Key::KEYPAD_7, "KP_7" },
        { Key::KEYPAD_8, "KP_8" },
        { Key::KEYPAD_9, "KP_9" },
        { Key::KEYPAD_DECIMAL, "KP_DECIMAL" },
        { Key::KEYPAD_DIVIDE, "KP_DIVIDE" },
        { Key::KEYPAD_MULTIPLY, "KP_MULTIPLY" },
        { Key::KEYPAD_SUBTRACT, "KP_SUBTRACT" },
        { Key::KEYPAD_ADD, "KP_ADD" },
        { Key::KEYPAD_ENTER, "KP_ENTER" },
        { Key::KEYPAD_EQUAL, "KP_EQUAL" },
        { Key::LEFT_SHIFT, "LEFT_SHIFT" },
        { Key::LEFT_CONTROL, "LEFT_CONTROL" },
        { Key::LEFT_ALT, "LEFT_ALT" },
        { Key::LEFT_SUPER, "LEFT_SUPER" },
        { Key::RIGHT_SHIFT, "RIGHT_SHIFT" },
        { Key::RIGHT_CONTROL, "RIGHT_CONTROL" },
        { Key::RIGHT_ALT, "RIGHT_ALT" },
        { Key::RIGHT_SUPER, "RIGHT_SUPER" },
        { Key::MENU, "MENU" }
    };

    std::unordered_map<int32_t, MouseKey> KeyMapper::toSGFMouseMap = {
        {GLFW_MOUSE_BUTTON_1, MouseKey::LEFT},
        {GLFW_MOUSE_BUTTON_2, MouseKey::RIGHT},
        {GLFW_MOUSE_BUTTON_3, MouseKey::MIDDLE},
        {GLFW_MOUSE_BUTTON_4, MouseKey::BUTTON_1},
        {GLFW_MOUSE_BUTTON_5, MouseKey::BUTTON_2},
        {GLFW_MOUSE_BUTTON_6, MouseKey::BUTTON_3},
        {GLFW_MOUSE_BUTTON_7, MouseKey::BUTTON_4},
        {GLFW_MOUSE_BUTTON_8, MouseKey::BUTTON_5},
    };

    std::unordered_map<MouseKey, int32_t> KeyMapper::toGLFWMouseMap = {
        {MouseKey::LEFT, GLFW_MOUSE_BUTTON_1},
        {MouseKey::RIGHT, GLFW_MOUSE_BUTTON_2},
        {MouseKey::MIDDLE, GLFW_MOUSE_BUTTON_3},
        {MouseKey::BUTTON_1, GLFW_MOUSE_BUTTON_4},
        {MouseKey::BUTTON_2, GLFW_MOUSE_BUTTON_5},
        {MouseKey::BUTTON_3, GLFW_MOUSE_BUTTON_6},
        {MouseKey::BUTTON_4, GLFW_MOUSE_BUTTON_7},
        {MouseKey::BUTTON_5, GLFW_MOUSE_BUTTON_8},
    };

    std::unordered_map<MouseKey, std::string> KeyMapper::toNameMouseMap = {
        {MouseKey::LEFT, "LEFT"},
        {MouseKey::RIGHT, "RIGHT"},
        {MouseKey::MIDDLE, "MIDDLE"},
        {MouseKey::BUTTON_1, "BUTTON_1"},
        {MouseKey::BUTTON_2, "BUTTON_2"},
        {MouseKey::BUTTON_3, "BUTTON_3"},
        {MouseKey::BUTTON_4, "BUTTON_4"},
        {MouseKey::BUTTON_5, "BUTTON_5"},
    };

    Key KeyMapper::toSGFKey(int32_t key) {
        return toSGFMap[key];
    }

    int32_t KeyMapper::toGLFWKey(Key key) {
        return toGLFWMap[key];
    }

    std::string KeyMapper::toName(Key key) {
        return toNameMap[key];
    }

    MouseKey KeyMapper::toSGFMouseKey(int32_t key) {
        return toSGFMouseMap[key];
    }

    int32_t KeyMapper::toGLFWMouseKey(MouseKey key) {
        return toGLFWMouseMap[key];
    }

    std::string KeyMapper::toName(MouseKey key) {
        return toNameMouseMap[key];
    }
}
